config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines thec root path route ("/")


  # root "articles#index"
  root to: 'lists#index'
  resources :lists, except: :index

  resources :movies, only: :index do
    resources :bookmarks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @movie = Movie.find(params[:movie_id])
    @bookmark = Bookmark.new
  end

  def create
    # raise
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie = Movie.find(params[:movie_id])
    @bookmark.list = List.find(params[:bookmark][:list_id])
    # raise
    if @bookmark.save!
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_lists

  def index
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: 303
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_lists
    @lists = List.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>new bookmark</h1>
<%= simple_form_for [@movie, @bookmark] do |f| %>
  <%= f.association :list %>
  <%= f.input_field :comment %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: url(https://images.squarespace-cdn.com/content/v1/589a866f725e250f86437b3d/1486522186367-LSI7L5ZVH8BBT8ZK9E0Z/beaver_log.jpg?format=1500w);">
  <div class="container">
    <h1>Would you help me build my <strong>Movie</strong> <strong>Dam</strong>?</h1>
    <p></p>
  </div>
</div>

<div class="container">

  <div class="m-5 d-flex justify-content-center align-item-center"><h1>My Dams</h1></div>

  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
    <div class="card-category mb-3 list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= nil ? "https://media.istockphoto.com/id/1271522601/photo/pop-corn-and-on-red-armchair-cinema.jpg?s=612x612&w=0&k=20&c=XwQxmfrHb-OwV5onPUW5ApB4RaGBK7poSIzZj4q_N_g=" : list.movies.all.first.poster_url if nil %>)"><%= list.name %></div>
    <% end %>
  <% end %>

  <%= link_to new_list_path do %>
    <div class="card-category mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">+</div>
  <% end %>

</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>

  <% @list.bookmarks.each do |bookmark| %>
    <div class="cards">
      <div class="card text-bg-dark">
        <%= image_tag bookmark.movie.poster_url %>
        <div class="card-img-overlay">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-text"><%= bookmark.movie.overview %></p>
          <p class="card-text"><small><%= '⭐️' * bookmark.movie.rating %>(<%= bookmark.movie.rating %>)</small></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/index.html.erb
<div class="container">
  <div class="mb-5"> </div>
  <div class="cards">
    <% @movies.each do |movie| %>
      <div class="card-trip">
        <%= image_tag movie.poster_url %>
        <div class="card-trip-infos">
          <div>
            <%= link_to "", new_movie_bookmark_path(movie), class: "fa-sharp fa-solid fa-bookmark bookmark-icon" %>
            <h2><%= movie.title %></h2>
            <p><%= movie.overview %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%# <div class="navbar navbar-expand-sm">
  <div class="container-fluid">
    <div class="nav-item dropdown"> %>
      <%#= image_tag "https://e7.pngegg.com/pngimages/158/181/png-clipart-north-american-beaver-graphy-illustration-cute-cartoon-beaver-material-cartoon-character-mammal.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <%# <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown"> %>
        <%#= link_to "Movies", movies_path, class: "dropdown-item" %>
        <%#= link_to "My Dam", "/", class: "dropdown-item" %>
        <%#= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
      <%# </div>
    </div>
  </div>
</div> %>




<nav class="navbar bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= '/' %>">Dam it!</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="fa-solid fa-bars"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= '/' %>">My Dams</a>
          </li>
          <li class="nav-item">
           <a class="nav-link" href=<%= movies_path %>>Collect Movie Logs</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>